spring:
    datasource:
        # the database for product
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.143.247.250:3306/WXDatabase?characterEncoding=utf8&useUnicode=true&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
        username: root
        password: mysqlServer1
        hikari:
            max-lifetime: 60000
            maximum-pool-size: 200
            connection-timeout: 30000
            minimum-idle: 10
            idle-timeout: 30000
            auto-commit: true
            connection-test-query: SELECT 1
