server:
    port: 8102
    tomcat:
        max-http-form-post-size: 8192
        max-http-header-size: 8192
        threads:
            max: 1000
        accept-count: 1000
        connection-timeout: 18000000
    ssl:
        key-store: classpath:nannayixiaobang.com.jks
        key-store-password: shtv4182zn
        key-store-type: JKS
        enabled: true


spring:
    profiles:
        active: prod
    jackson:
        time-zone: GMT+8
        date-format: yyyy/MM/dd HH:mm:ss
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    redis:
        database: 0
        host: 43.143.247.250
        port: 6379
        timeout: 18000000
        password: redisServer1
        jedis:
            pool:
                # 连接池最大连接数（负值表示没限制）
                max-active: -1
                # 连接池最大阻塞等待时间（负值表示没限制）
                max-wait: -1
                # 连接池中的最大空闲连接
                max-idle: 10
                # 连接池中的最小空闲连接
                min-idle: 0

    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

mybatis:
    mapper-locations:
        - classpath:mapper/*.xml
    # 对实体类标记别名的包, 默认为类名的首字母小写
    type-aliases-package: com.weixin.njuteam.entity.po
    configuration:
        # 下划线自动转驼峰
        map-underscore-to-camel-case: true

jwt:
    user:
        secret: 756264cf-376b-48cb-9697-794eb1c432be
        # token签发过期的时间 86400000ms = 24h
        expire: 86400000
    manager:
        secret: c5a557a4-b223-4f29-841a-aff6aa8f02fc
        # token签发过期的时间 86400000ms = 24h
        expire: 86400000


weixin:
    # appid
    appId: wx863ec99d19ec3d90
    # secrete
    secret: d194e8e33e2597b9166984117df1d415
    # grant_type
    grantType: client_credential

baidu:
    # appid
    appId: 29373108
    APIKey: uHdgFhLlYkhz1rQENbMileep
    secretKey: K26vbrWHxF6nybMcWqQx1I1irCmRW5IQ

logging:
    file:
        name: /usr/local/spring.log

jasypt:
    encryptor:
        password: a74e2f91-c034-4f2c-af5a-8f845b54a539
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator
        key-obtention-iterations: 1000
        pool-size: 1
        string-output-type: base64
        provider-name: SunJCE
        salt-generator-classname: org.jasypt.salt.RandomSaltGenerator


